name: Main workflow
on:
  pull_request:
    branches: main
  push:
   branches: main
env: # Set the secret as an input
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }} #Nees to be set to be made available to the workflow
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4  
      - name: Build
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - name: Upload repo
        uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
         name: code
         path: .
      - name: Run linting
        uses: super-linter/super-linter@v5.7.2
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
  Docker-image:
      runs-on: ubuntu-latest
      needs: [Build]
      permissions:
       packages: write
      steps:
        - name: Download code
          uses: actions/download-artifact@v4
          with:
           name: code
           path: .
        - name: build docker
          run: bash ci/build-docker.sh
        - name: push docker
          run: bash ci/push-docker.sh
  Component-test:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute component test
        run: bash ci/component-test.sh
  Performace-test:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Execute performance test
        run: bash ci/performance-test.sh
    
  
          
